### ISSUE TITLE
Can't be run because it's not signed

### ISSUE THREAD

**Issue by jkbecker** [A-mIn3/WINspect#10]
Just downloading the file, a vanilla Windows 10 installation will not allow this to run.

1. how can this be prevented?
2. could this be accomodated in the README?

![image](https://user-images.githubusercontent.com/31668498/38523348-2bf44c0e-3c19-11e8-95bf-44f5b563edf2.png)

Cheers

Johannes

**Comment by ghost** [comment]
open Powershell as Admin enter  "Set-ExecutionPolicy Bypass" and then run the Script.
The default Settings on Windows 10 is "Restricted" this is why you get this error
alternative you could sign the Script with your own Cert from your CA in the Domain
