### ISSUE TITLE
Totally bails out when no domain found

### ISSUE THREAD

**Issue by ChaosAdventurer** [A-mIn3/WINspect#4]
while this interesting tool with a readme thatclaims "Howerver, some of the functions still apply for standalone workstations." The actual usage appears to be different. (the miss spelled however I'll assume is just an extra left over pirate day R in there)
on a Windows 7 pro system I got freshly downloaded WINspect bailing out when it couldn't find any domain as per below.
It is almost as if only systems with AD need securing, not Windows itself in all those places where they run without any AD in sight. 

Starting Audit at 11/09/2017 3:46:03 PM
-------------------------------------
[?] Checking for administrative privileges ..
[?] Checking for Default PowerShell version ..
       [+] ----->  PowerShell v2
[?] Detecting system role ..
       [-] This script needs access to the domain. It can only be run on a domain member machine.
Type any key to continue ..:
PS D:\util\WINspect>

**Comment by aoprea1982** [comment]
<<< have seen the same issue with Windows 10 x64 pro >>>
![winspect6](https://user-images.githubusercontent.com/16059481/30303135-cd4f6700-97a0-11e7-9a5a-676b164cbf33.jpg)

**Comment by A-mIn3** [comment]
The tool is not to be used "as is" for standalone wks.
In readme : "However, some of the functions still apply for standalone workstations."
This means that if you want to use the script in a standalone wk, you only need to call functions that do not deal with the domain, which is not the case in this instance (we are checking for local groups with domain members and need access to the domain to translate some SIDs).

**Comment by A-mIn3** [comment]
Anyway I think it will be more accurate to change it  to be in accordance with the README.
I have changed the sequence of checks to support std wks.
KR.

**Comment by ChaosAdventurer** [comment]
Works much better now, it checked a useful set of things and didn't find any thing that needed my attention.  Thank you very much.
The only issues I see at this point are just extra(deletable) character typos in the README.md     
 the extra r in the Description section in "Howerver"
 and the extra e in the Contributions section in "suggeste"

**Comment by aoprea1982** [comment]
Thank you. 
Works like a charm.
